### ISSUE TITLE
How to extract the saturation value?   

### ISSUE THREAD

**Issue by yakir12** [ap--/python-oceanoptics#23]
How can I extract the maximal value the spectrometer is saturated at? This depends on the type of the stored integers (UInt10, UInt12, UInt16 etc)...

**Comment by ap--** [comment]
Please have a look at [python-seabreeze](https://github.com/ap--/python-seabreeze) which is the successor of python-oceanoptics. It's all implemented in the pyseabreeze backend.

The different spectrometer models have different ADC resolutions (10bit, 12bit, 16bit), which define the maximum value. In addition some models store a saturation value (smaller than the biggest possible return value) to indicate if the sensor saturates at lower ADC values.

**Comment by yakir12** [comment]
Fantastic. I'm assuming the variable I want is `_MAX_PIXEL_VALUE`.
I'm a total noob with Python, and I'm doing all of this from Julia with PyCall. Everything works great, but how do I actually access `_MAX_PIXEL_VALUE`?
```python
>>> spec._MAX_PIXEL_VALUE()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Spectrometer' object has no attribute '_MAX_PIXEL_VALUE'
```
Excuse the noobness...

**Comment by ap--** [comment]
Continues in ap--/python-seabreeze#17.
